### ISSUE TITLE
Look into how the files are sent to the wash u browser

### ISSUE THREAD

**Issue by sehilyi** [hms-dbmi/cistrome-higlass-wrapper#101]

**Comment by keller-mark** [comment]
We want to determine how easy it would be to send the data to the higlass server in the same way, so that the data can be viewed in the higlass wrapper component.

**Comment by keller-mark** [comment]
If a separate higlass server instance for this cistrome use case is required, we should determine who is responsible for managing the instance.

**Comment by keller-mark** [comment]
One issue: we still want to aggregate the files from the selected samples into a `multivec` file, both for performance reasons

>  If we try to display too many individual bigWig files, however, the performance will suffer due to the many files that need to be opened and read.
> A better solution is to consolidate the data into a single "multivec" file that can be queried once to obtain values across hundreds of datasets... - https://hms-dbmi.github.io/cistrome-higlass-demo/

and because we have been developing the wrapper component with the assumption that a `horizontal-multivec` track is present in the higlass view.

Another thing to keep in mind is that in addition to the .bed or .bigWig files containing the data, we also need access to the metadata for each sample, which ultimately should be stored in the .multivec file

**Comment by sehilyi** [comment]
Can the current .multivec format store metadata for samples (rows)?

**Comment by keller-mark** [comment]
Yes, the current .multivec format stores both the tile data and the sample/row metadata. It is really just a HDF5 file, and can be opened in python using h5py http://docs.h5py.org/en/stable/

**Comment by keller-mark** [comment]
Started a wiki page here to gather information about the cistrome DB API https://github.com/hms-dbmi/cistrome-higlass-wrapper/wiki/Cistrome-DB-Data
