### ISSUE TITLE
Fix positioning of genome interval selection genome coordinate text

### ISSUE THREAD

**Issue by keller-mark** [hms-dbmi/cistrome-higlass-wrapper#183]
<img width="737" alt="Screen Shot 2020-03-10 at 12 39 21 PM" src="https://user-images.githubusercontent.com/7525285/76336299-2f061680-62cc-11ea-87e4-0d0ccd7e959d.png">

I think we should actually think about getting rid of the "Select current interval" button and see if we can implement a higlass API feature to allow us to add custom options to the higlass context menu. This would clear up some screen space and we could put it here for example

<img width="656" alt="Screen Shot 2020-03-10 at 12 40 56 PM" src="https://user-images.githubusercontent.com/7525285/76336634-adfb4f00-62cc-11ea-95f7-689a4b9e3d39.png">

**Comment by sehilyi** [comment]
In this point, I think we need to think about how to better support interactions for genomic selection. 

I think enabling users to select the region of their interest directly on the visualization (e.g., dragging) is desirable instead of initially selecting the whole region that a user is currently seeing. Because, in this way, users can more easily and intuitively select regions whenever they see interesting pattern in the heatmaps.

Because higlass already use dragging interaction on itself, we might add a narrow horizontal bar on the bottom (just like the current `horizontal-chromosome-labels`?) and enable dragging along the x-axis on that track to select the column regions of interest.

**Comment by keller-mark** [comment]
I like the narrow horizontal bar idea since this would also eliminate the need for the button

**Comment by sehilyi** [comment]
Related to #147

**Comment by sehilyi** [comment]
I will put the narrow horizontal bars on the bottom of individual _views_, not individual _multivec tracks_.

**Comment by keller-mark** [comment]
That sounds good.
