### ISSUE TITLE
Enable creating a genomic interval selection that spans across multiple tracks

### ISSUE THREAD

**Issue by sehilyi** [hms-dbmi/cistrome-higlass-wrapper#69]
- Change name of button to “select current interval” (fixed in #80)
- Enable creating a genomic interval selection that spans across multiple tracks
    - Look into different implementations for genomic interval selection, since will probably need to implement the selection in the wrapper component, rather than using the `viewport-projection-horizontal` higlass track.

Refer to HiGlass 1.4 new feature: http://higlass.io/app/?config=cjmbb_MSQ56_Pi9zX9_n3Q

**Comment by keller-mark** [comment]
Related to https://github.com/higlass/higlass/pull/860

**Comment by keller-mark** [comment]
I have made a lot of progress here in allowing multiple interval selections by implementing a new selection component using d3-brush, but I have thought about it again and I think that this is the wrong approach.
Instead I am going to start over and try again to use the built-in higlass `viewport-projection-horizontal` track since that also provides the linking functionality if a user wants to link the current view to another view and lock the location or zoom level.

I think the best way to do this is to work on adding a new higlass track option called `initialXDomain` (similar to the higlass `view` object attribute with the same name), and enable this field to be used when the `fromViewUid` field is `null` (because there is no linked view).

I also noticed yesterday that the higlass API has a function called `activateTool` ([code here](https://github.com/higlass/higlass/blob/develop/app/scripts/api.js#L518)) which has a `'select'` option, but when I called the function and then clicked to make a selection, higlass crashed.

**Comment by sehilyi** [comment]
I am sad that we cannot use the code you've implemented, but it sounds reasonable to use higlass core functions instead as you said. Selection will be rendered synchronously with higlass tracks, and we can use the 'projection' features in higlass for multiple track usages.

**Comment by keller-mark** [comment]
This higlass change is intended to support this feature https://github.com/higlass/higlass/pull/864

**Comment by keller-mark** [comment]
I am going to close this since now we just need to wait until the higlass pull request has been merged and included in a new higlass release

**Comment by keller-mark** [comment]
I will make a new issue for that
